default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: BlogOnRails_development
  username: <%= Rails.application.credentials.aws[:db_user] %>
  password: <%= Rails.application.credentials.aws[:db_password] %>
  encoding: unicode
  host: localhost
  pool: 5

test:
  <<: *default
  database: BlogOnRails_test
  username: <%= Rails.application.credentials.aws[:db_user] %>
  password: <%= Rails.application.credentials.aws[:db_password] %>
  encoding: unicode
  host: localhost
  pool: 5

production:
  <<: *default
  database: BlogOnRails_production
  username: BlogOnRails
  password: <%= ENV['BLOGONRAILS_DATABASE_PASSWORD'] %>